const registerHealthzRoute = require('./healthz')
const registerEdipTokenGetRoute = require('./edip/tokenGet')
const registerEdipTokenRefreshRoute = require('./edip/tokenRefresh')
const registerCardpinValidateRoute = require('./ewl/bal/cardpinValidate')
const registerTeamHierarchyRoute = require('./ewl/mktRm/teamHierarchy')
const registerMemberProfileRoute = require('./ewl/edip/memberProfile')
const registerPromotionAllRoute = require('./ewl/bal/promotionAll')
const registerPlayerImageRoute = require('./ewl/bal/playerImage')
const registerPlayerEarnRoute = require('./ewl/bal/playerEarn')
const registerPrizeRedeemRoute = require('./ewl/bal/prizeRedeem')
const registerPointVoidRoute = require('./ewl/bal/pointVoid')
const registerRedeemedPromotionDetailRoute = require('./ewl/bal/redeemedPromotionDetail')
const registerPlayerPromotionRedeemRoute = require('./ewl/bal/playerPromotionRedeem')
const registerRedeemedPromotionVoidRoute = require('./ewl/bal/redeemedPromotionVoid')
const registerPrizeRedemptionsSyncRoute = require('./api/v1/prizeRedemptionsSync')

function registerRoutes({ app, context, ldapService }) {
  registerHealthzRoute({ app, ldapService })
  registerEdipTokenGetRoute({ app, context })
  registerEdipTokenRefreshRoute({ app, context })
  registerCardpinValidateRoute({ app, context })
  registerTeamHierarchyRoute({ app, context })
  registerMemberProfileRoute({ app, context })
  registerPromotionAllRoute({ app, context })
  registerPlayerImageRoute({ app, context })
  registerPlayerEarnRoute({ app, context })
  registerPrizeRedeemRoute({ app, context })
  registerPointVoidRoute({ app, context })
  registerRedeemedPromotionDetailRoute({ app, context })
  registerPlayerPromotionRedeemRoute({ app, context })
  registerRedeemedPromotionVoidRoute({ app, context })
  registerPrizeRedemptionsSyncRoute({ app, context })
}

module.exports = { registerRoutes }
